### ISSUE TITLE
read_events is not returning multiple events

### ISSUE THREAD

**Issue by noboruma** [aya-rs/aya#148]
Hello there,

I am currently experimenting with the `aya-echo-tracepoint` example.
Full code is available here: https://github.com/noboruma/open-tracer/tree/open_tracer
According to the eBPF documentation, we can send multiple events on the perf event ring buffer, via  `bpf_perf_event_output`.
However, the current `read_events` implementation is reading one event at a time, despite reserving enough memory. As a result, many events are lost unexpectedly.

**Context**:
- Aya-version: 0.10.6

**eBPF code**:
```
#[map]
static mut BUFFER: PerCpuArray<Event> = PerCpuArray::with_max_entries(1, 0);
...
EVENTS.output(&ctx, &event, 0);
```

**User code**:
```
let mut buffers = [BytesMut::with_capacity(size_of::<Event>()*10)];
let events = buf_per_cpu.read_events(&mut buffers).await.unwrap();
```

**Expected results**:
```
events.read == 10
```

**Actual results**:
```
events.read == 1
events.lost > 10
```

**Comment by alessandrod** [comment]
`read_events()` does read multiple events, the problem is that the events you're sending are very large, and they barely fit the ring buffer. You should increase the buffer size by using a higher page count (the default is 2), see https://docs.rs/aya/latest/aya/maps/perf/struct.AsyncPerfEventArray.html#method.open, and probably use a len prefixed approach for paths instead of using a large fixed size array in https://github.com/noboruma/open-tracer/blob/0b632917377e9a3a5616c39d60586ffdb829dc0a/echo-common/src/lib.rs#L3

**Comment by noboruma** [comment]
Thank you @alessandrod, changing the page count did the trick! I completely missed that option.
I will look at the len prefixed approach for the path - my only worry is that such approach would require extra allocation and extra swapping on the eBPF side.
