### ISSUE TITLE
Proposal: Add a cargo-generate template

### ISSUE THREAD

**Issue by dave-tucker** [aya-rs/aya#41]
Similar to `cargo-bpf` from RedBPF.
Seeing as setting up the project structure is ~non-trivial it would be nice to be able to initialise a new Aya project quickly.
I think that before this is implemented we'd want to ensure that the "recommend" structure wouldn't change too much.

After some experimentation, this is what I've settled on, but I'd be interested to get input from other users:

```bash
.
├── bpf
│   ├── Cargo.lock
│   ├── Cargo.toml
│   ├── build.rs
│   └── src
│       └── xdp
│           └── main.rs
│       └── lib.rs
├── Cargo.lock
├── Cargo.toml
├── README.md
├── types
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
└── user
    ├── Cargo.lock
    ├── Cargo.toml
    └── src
        └── xdp.rs
```

- `bpf` is the bpf program(s)
- `types` is any shared types between bpf and userspace
- `user` is the userspace program(s)

Both the `user` and `types` package are part of the same workspace as they can both be built with cargo build. `bpf` however requires rust nightly and some unstable cargo features, and therefore must be in it’s own workspace. With the `bpf/.cargo/config.toml` setting the necessary flags, the current workflow is currently something like this:

```
pushd bpf
cargo +nightly build
popd
cargo build
```

Note: This doesn't factor in any of the ideas around testing of bpf programs from the host... which requires dropping the `bpf/.cargo/config.toml` :thinking:

**Comment by alessandrod** [comment]
As the original author of `cargo-bpf` I have strong feelings about this!  In retrospect, I think that the project scaffolding part was a mistake, and we should have used [cargo-generate](https://github.com/cargo-generate/cargo-generate) instead. 

As for the project structure, I think it's important that the crates have unique names, as opposed to the generic `bpf` `user` etc. Generic names don't work with workspaces, and I don't think it'll be uncommon to have a few aya projects in the same workspace (I already do!).

I've tried a few layouts, and what I'm using now is:

- `<project name>/` - the userspace crate
- `<project name>-ebpf/`  - the eBPF crate
- `<project name>-common/` - crate used by both userspace and eBPF

I wouldn't call it `-types` since you can share code too (and I often do).

Btw a nice thing about using `cargo-generate` is that you can point it to a git url, so if someone's not happy with the structure we'll end up recommending, they can use another template.

**Comment by dave-tucker** [comment]
Updated the issue name to reflect using cargo-generate instead

**Comment by dave-tucker** [comment]
Initial template is here! https://github.com/dave-tucker/aya-template
I'd love to donate it here and/or to a github org so it's closer to the source code.
It depends on my branch of `cargo-generate` for now, until my PR is accepted upstream (1/2 merged so far).

**Comment by alessandrod** [comment]
I think we can close this now?

**Comment by dave-tucker** [comment]
Yep!
