### ISSUE TITLE
unknown func bpf_get_current_pid_tgid - but it actually exists

### ISSUE THREAD

**Issue by emanuele-em** [aya-rs/aya#864]
I'm building a TC Classifier (Egress), I used the template code and everything works fine BUT if I add `BpfContext` with `let pid = ctx.pid()` it breaks.

Code:
```rust
#![no_std]
#![no_main]

use aya_bpf::{macros::classifier, programs::TcContext, BpfContext};
use aya_log_ebpf::info;

#[classifier]
pub fn interceptor(ctx: TcContext) -> i32 {
    match try_interceptor(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}

fn try_interceptor(ctx: TcContext) -> Result<i32, i32> {
    let pid = ctx.pid();
    info!(&ctx, "received a packet");
    Ok(0)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! {
    unsafe { core::hint::unreachable_unchecked() }
}
```

Error:

```
Finished dev [unoptimized + debuginfo] target(s) in 0.08s
[sudo] password for emanuele:
Error: the BPF_PROG_LOAD syscall failed. Verifier output: 0: R1=ctx(off=0,imm=0) R10=fp0
0: (bf) r6 = r1                       ; R1=ctx(off=0,imm=0) R6_w=ctx(off=0,imm=0)
1: (85) call bpf_get_current_pid_tgid#14
unknown func bpf_get_current_pid_tgid#14
verification time 19 usec
stack depth 0
processed 2 insns (limit 1000000) max_states_per_insn 0 total_states 0 peak_states 0 mark_read 0


Caused by:
    Invalid argument (os error 22)
Failed to run `sudo -E target/debug/interceptor --iface wlo1`
```

is it a problem with linker? I miss something?

**Comment by alessandrod** [comment]
This is a bug in TcContext, it should return the skb.pid and not use the helper. Want to try to make a patch? 😊

**Comment by emanuele-em** [comment]
@alessandrod sure!

**Comment by alessandrod** [comment]
As per discord conversation, I was wrong, there's no way to directly get the pid from an egress tc program. The only way is to correlate local_port with a pid manually.

**Comment by gotoolkits** [comment]
use aya_bpf::helpers::bpf_get_current_pid_tgid
...
let pid = bpf_get_current_pid_tgid() as u32;

The same error has occurred. May I ask what the reason is?
----
15: (15) if r1 == 0x7 goto pc-8
 R0_w=inv0 R1_w=inv(id=0) R2_w=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6_w=ctx(id=0,off=0,imm=0) R7_w=inv2 R10=fp0 fp-16=??mmmmmm fp-24=mmmmmmmm
16: (55) if r1 != 0x8 goto pc+62
 R0=inv0 R1=inv8 R2=inv(id=0,umax_value=255,var_off=(0x0; 0xff)) R6=ctx(id=0,off=0,imm=0) R7=inv2 R10=fp0 fp-16=??mmmmmm fp-24=mmmmmmmm
**17: (85) call bpf_get_current_pid_tgid#14
unknown func bpf_get_current_pid_tgid#14**
verification time 48 usec
stack depth 24
processed 18 insns (limit 1000000) max_states_per_insn 0 total_states 2 peak_states 2 mark_read 1

**Comment by gotoolkits** [comment]
Oh, I misunderstood. You can use TracepointContext to correct it.
-----
#[tracepoint]
pub fn tracepoint_demo(ctx: TracePointContext) -> u32 {
    match try_tracepoint_demo(ctx) {
        Ok(ret) => ret,
        Err(ret) => ret,
    }
}
