### ISSUE TITLE
Build error on OS FreeBSD

### ISSUE THREAD

**Issue by matissecallewaert** [aya-rs/aya#951]
When trying to cross build my Aya based project on Ubuntu for FreeBSD with following command:

```sh
cargo build --release --target=x86_64-unknown-freebsd
```

I got following error:

```sh
error[E0432]: unresolved imports `libc::nlattr`, `libc::nlmsgerr`, `libc::nlmsghdr`, `libc::sockaddr_nl`, `libc::AF_NETLINK`, `libc::ETH_P_ALL`, `libc::IFLA_XDP`, `libc::NETLINK_EXT_ACK`, `libc::NETLINK_ROUTE`, `libc::NLA_ALIGNTO`, `libc::NLA_F_NESTED`, `libc::NLA_TYPE_MASK`, `libc::NLMSG_DONE`, `libc::NLMSG_ERROR`, `libc::NLM_F_ACK`, `libc::NLM_F_CREATE`, `libc::NLM_F_DUMP`, `libc::NLM_F_ECHO`, `libc::NLM_F_EXCL`, `libc::NLM_F_MULTI`, `libc::NLM_F_REQUEST`, `libc::RTM_DELTFILTER`, `libc::RTM_GETTFILTER`, `libc::RTM_NEWQDISC`, `libc::RTM_NEWTFILTER`, `libc::RTM_SETLINK`, `libc::SOL_NETLINK`
  --> /home/username/.cargo/git/checkouts/aya-c55fbc69175ac116/3808ad5/aya/src/sys/netlink.rs:10:18
   |
10 |     getsockname, nlattr, nlmsgerr, nlmsghdr, recv, send, setsockopt, sockaddr_nl, socket,
   |                  ^^^^^^  ^^^^^^^^  ^^^^^^^^                          ^^^^^^^^^^^ no `sockaddr_nl` in the root
   |                  |       |         |
   |                  |       |         no `nlmsghdr` in the root
   |                  |       no `nlmsgerr` in the root
   |                  no `nlattr` in the root
11 |     AF_NETLINK, AF_UNSPEC, ETH_P_ALL, IFF_UP, IFLA_XDP, NETLINK_EXT_ACK, NETLINK_ROUTE,
   |     ^^^^^^^^^^             ^^^^^^^^^          ^^^^^^^^  ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^ no `NETLINK_ROUTE` in the root
   |     |                      |                  |         |
   |     |                      |                  |         no `NETLINK_EXT_ACK` in the root
   |     |                      |                  no `IFLA_XDP` in the root
   |     |                      no `ETH_P_ALL` in the root
   |     no `AF_NETLINK` in the root
12 |     NLA_ALIGNTO, NLA_F_NESTED, NLA_TYPE_MASK, NLMSG_DONE, NLMSG_ERROR, NLM_F_ACK, NLM_F_CREATE,
   |     ^^^^^^^^^^^  ^^^^^^^^^^^^  ^^^^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^  ^^^^^^^^^^^^
   |     |
   |     no `NLA_ALIGNTO` in the root
13 |     NLM_F_DUMP, NLM_F_ECHO, NLM_F_EXCL, NLM_F_MULTI, NLM_F_REQUEST, RTM_DELTFILTER, RTM_GETTFILTER,
   |     ^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^^^^  ^^^^^^^^^^^^^  ^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^
14 |     RTM_NEWQDISC, RTM_NEWTFILTER, RTM_SETLINK, SOCK_RAW, SOL_NETLINK,
   |     ^^^^^^^^^^^^  ^^^^^^^^^^^^^^  ^^^^^^^^^^^            ^^^^^^^^^^^
```

I know Aya is made only using the libc library, is libc not supported on FreeBSD or is it not the same as in Ubuntu?

Does anyone know how to fix this or is FreeBSD an OS that is not supported in Aya?

**Comment by vadorovsky** [comment]
First of all, is the upstream FreeBSD even supporting eBPF at all? I see that there was some work being done there, but it doesn't seem like it was ever upstreamed.

https://wiki.freebsd.org/SummerOfCode2020Projects/eBPFXDPHooks
https://papers.freebsd.org/2018/bsdcan/hayakawa-ebpf_implementation_for_freebsd/

Getting straight to the error you're getting - `libc` crate defines these symbols only for Linux. Most likely for a good reason, most likely because they just don't exist. `IFLA_XDP`, `AF_NETLINK` etc. come from the Linux kernel headers. They are literally in this file:

https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/mod.rs.html#1944

If you are interested in fixing Aya for FreeBSD:

* First, you'd need to make sure that eBPF is actually supported in FreeBSD upstream kernel, or that the `generic-ebpf` thing or any fork of FreeBSD is ready enough that it makes sense to make this effort.
  * From my understanding, all the PoCs of eBPF were only about XDP, so that would be the only program supported.
* Then you'd need to:
  * Search for replacements for all missing symbols, you're getting errors about.
  * Make sure they're in `libc` crate. If not, add them there first.
  * Use them in Aya.

**Comment by vadorovsky** [comment]
OTOH, we should totally support the opposite action - cross-compiling for Linux on FreeBSD host. If that doesn't work, that would be a bug to fix. In constrast to building for FreeBSD target, which is a feature request.

**Comment by vadorovsky** [comment]
Closing for now, feel free to re-open if there is any eBPF solution in FreeBSD we could run against.
